### PR TITLE
Fix "standalone" include issue by adding header boost/type_traits/is_…

### PR DESCRIPTION
**Pull request by matovitch**
PR fixing issue: https://github.com/boostorg/tokenizer/issues/9

(Quite new to submitting PR, let me know if anything is wrong)

### CODE REVIEW

**Comment by jeking3** [comment]
Did this run CI builds?  They should be configured but I see no status.

**Comment by eldiener** [comment]
I tested it locally. I have not seen CI builds for awhile in any changed library.

**Comment by jeking3** [comment]
I just toggled the Travis and Appveyor CI builds off and on.  CI should run on PRs.

Travis: PASS https://travis-ci.org/boostorg/tokenizer/builds/444727886
AppVeyor: FAIL https://ci.appveyor.com/project/jeking3/tokenizer-c6pnd/builds/19694861

Need to see if it's environmental.

**Comment by jeking3** [comment]
Re-running AppVeyor: https://ci.appveyor.com/project/jeking3/tokenizer-c6pnd/builds/19702415

**Pull request merged**
